from __future__ import annotations

"""
Adapter around core Trajectoids path-to-rotation logic.

The functions `_rotation_from_point_to_point`, `rotations_to_origin`, `trace_on_sphere`,
and mismatch/scale checks are direct algorithmic ports from the upstream
`compute_trajectoid.py` implementation in `yaroslavsobolev/trajectoids`.
"""

from dataclasses import dataclass
from pathlib import Path
import struct
from typing import List, Tuple

import numpy as np


EPS = 1e-9


def _get_minimize_scalar():
    try:
        from scipy.optimize import minimize_scalar as _minimize_scalar

        return _minimize_scalar
    except Exception:  # pragma: no cover - optional fallback if scipy is unavailable
        return None


@dataclass
class ValidationResult:
    errors: List[str]
    suggestions: List[str]
    path_length: float
    closure_gap: float
    spacing_ratio: float


@dataclass
class GenerationResult:
    vertices: np.ndarray
    faces: np.ndarray
    scale: float
    mismatch_angle: float
    endpoint_gap: float
    resampled_points: np.ndarray
    normals: np.ndarray
    # Curve on the trajectoid surface: the locus of points that touch the
    # ground in succession while the body rolls along the input trajectory.
    # Shape (N, 3), expressed in the body-fixed frame at the starting pose.
    surface_contact_curve: np.ndarray


@dataclass
class RollSimulationResult:
    translations_xyz: np.ndarray
    rotations: np.ndarray
    trajectory_xy: np.ndarray
    achieved_roll_angle_rad: float
    completed_target: bool
    message: str


def export_binary_stl(
    vertices: np.ndarray,
    faces: np.ndarray,
    output_path: str | Path,
    solid_name: str = "trajectoid",
) -> Path:
    verts = np.asarray(vertices, dtype=float)
    if verts.ndim != 2 or verts.shape[1] != 3:
        raise ValueError("vertices must be an Nx3 array.")
    if not np.all(np.isfinite(verts)):
        raise ValueError("vertices must contain finite values.")

    faces_array = np.asarray(faces)
    if faces_array.ndim != 2 or faces_array.shape[1] != 3:
        raise ValueError("faces must be an Mx3 array.")

    if np.issubdtype(faces_array.dtype, np.integer):
        face_indices = faces_array.astype(np.int64, copy=False)
    elif np.issubdtype(faces_array.dtype, np.floating):
        if not np.all(np.isfinite(faces_array)):
            raise ValueError("faces must contain finite values.")
        rounded = np.rint(faces_array)
        if not np.allclose(faces_array, rounded):
            raise TypeError("faces must contain integer-like indices.")
        face_indices = rounded.astype(np.int64)
    else:
        raise TypeError("faces must contain integer-like indices.")

    if face_indices.size > 0:
        if np.any(face_indices < 0) or np.any(face_indices >= verts.shape[0]):
            raise ValueError("faces reference vertex indices outside the valid range.")

    out_path = Path(output_path).expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    n_faces = int(face_indices.shape[0])
    triangles = verts[face_indices] if n_faces > 0 else np.empty((0, 3, 3), dtype=float)
    normals = np.zeros((n_faces, 3), dtype=np.float32)
    if n_faces > 0:
        edge_ab = triangles[:, 1] - triangles[:, 0]
        edge_ac = triangles[:, 2] - triangles[:, 0]
        raw_normals = np.cross(edge_ab, edge_ac)
        lengths = np.linalg.norm(raw_normals, axis=1)
        valid = lengths > EPS
        if np.any(valid):
            normals[valid] = (raw_normals[valid] / lengths[valid, None]).astype(np.float32)

    facet_dtype = np.dtype(
        [
            ("normal", "<f4", (3,)),
            ("v0", "<f4", (3,)),
            ("v1", "<f4", (3,)),
            ("v2", "<f4", (3,)),
            ("attr", "<u2"),
        ]
    )
    facets = np.zeros(n_faces, dtype=facet_dtype)
    if n_faces > 0:
        facets["normal"] = normals
        facets["v0"] = triangles[:, 0].astype(np.float32, copy=False)
        facets["v1"] = triangles[:, 1].astype(np.float32, copy=False)
        facets["v2"] = triangles[:, 2].astype(np.float32, copy=False)

    safe_name = "".join(ch for ch in str(solid_name) if ch.isascii()).strip() or "trajectoid"
    header_text = f"Binary STL generated by trajectoids: {safe_name}"
    header = header_text.encode("ascii", errors="ignore")[:80].ljust(80, b"\0")

    with out_path.open("wb") as handle:
        handle.write(header)
        handle.write(struct.pack("<I", n_faces))
        handle.write(facets.tobytes())

    return out_path.resolve()


def path_length(points: np.ndarray) -> float:
    if points.shape[0] < 2:
        return 0.0
    return float(np.sum(np.linalg.norm(np.diff(points, axis=0), axis=1)))


def resample_uniform(points: np.ndarray, n_points: int, closed: bool = False) -> np.ndarray:
    if points.shape[0] < 2:
        return points.copy()
    pts = np.asarray(points, dtype=float)
    if closed and np.linalg.norm(pts[0] - pts[-1]) > EPS:
        pts = np.vstack([pts, pts[0]])
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    cumulative = np.concatenate([[0.0], np.cumsum(seg)])
    total = cumulative[-1]
    if total < EPS:
        return pts.copy()
    count = n_points + 1 if closed else n_points
    targets = np.linspace(0.0, total, count)
    xs = np.interp(targets, cumulative, pts[:, 0])
    ys = np.interp(targets, cumulative, pts[:, 1])
    out = np.column_stack([xs, ys])
    if closed:
        out = out[:-1]
    return out


def smooth_path(points: np.ndarray, passes: int = 2, closed: bool = False) -> np.ndarray:
    pts = np.asarray(points, dtype=float)
    if pts.shape[0] < 3 or passes <= 0:
        return pts.copy()
    for _ in range(passes):
        if closed:
            n = pts.shape[0]
            out = []
            for i in range(n):
                p = pts[i]
                q = pts[(i + 1) % n]
                out.append(0.75 * p + 0.25 * q)
                out.append(0.25 * p + 0.75 * q)
            pts = np.asarray(out, dtype=float)
        else:
            out = [pts[0]]
            for i in range(pts.shape[0] - 1):
                p = pts[i]
                q = pts[i + 1]
                out.append(0.75 * p + 0.25 * q)
                out.append(0.25 * p + 0.75 * q)
            out.append(pts[-1])
            pts = np.asarray(out, dtype=float)
    return pts


def curvature_profile(points: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(points, dtype=float)
    if pts.shape[0] < 3:
        return np.array([]), np.array([])
    ds = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    s = np.concatenate([[0.0], np.cumsum(ds)])
    d1 = np.gradient(pts, axis=0)
    d2 = np.gradient(d1, axis=0)
    numerator = np.abs(d1[:, 0] * d2[:, 1] - d1[:, 1] * d2[:, 0])
    denominator = np.power(d1[:, 0] ** 2 + d1[:, 1] ** 2, 1.5) + EPS
    kappa = numerator / denominator
    return s, kappa


def validate_path(
    points: np.ndarray,
    require_closed: bool = True,
    closure_fraction_tolerance: float = 0.03,
    max_spacing_ratio: float = 10.0,
) -> ValidationResult:
    pts = np.asarray(points, dtype=float)
    errors: List[str] = []
    suggestions: List[str] = []
    if pts.shape[0] < 8:
        errors.append("Curve has too few points to build a stable trajectoid.")
        suggestions.append("Draw a longer curve or use the resample tool to increase point count.")
        return ValidationResult(errors, suggestions, 0.0, 0.0, 0.0)

    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    if np.any(seg < EPS):
        errors.append("Curve contains repeated points or zero-length segments.")
        suggestions.append("Use erase/select to clean duplicates, then run smooth/resample.")

    plen = float(np.sum(seg))
    if plen < EPS:
        errors.append("Curve length is effectively zero.")
        suggestions.append("Draw a larger curve with visible extent.")

    closure_gap = float(np.linalg.norm(pts[0] - pts[-1]))
    if require_closed and plen > EPS and closure_gap > closure_fraction_tolerance * plen:
        errors.append("Curve must be periodic/closed for this generation mode.")
        suggestions.append("Close endpoints with select/move, or disable closed-curve mode.")

    min_seg = float(np.min(seg)) if seg.size > 0 else 0.0
    max_seg = float(np.max(seg)) if seg.size > 0 else 0.0
    spacing_ratio = max_seg / max(min_seg, EPS)
    if spacing_ratio > max_spacing_ratio:
        suggestions.append("Point spacing is uneven; run uniform resample before generation.")

    return ValidationResult(errors, suggestions, plen, closure_gap, spacing_ratio)


def _rodrigues_rotation_matrix(axis: np.ndarray, angle: float) -> np.ndarray:
    axis = np.asarray(axis, dtype=float)
    norm = np.linalg.norm(axis)
    if norm < EPS or abs(angle) < EPS:
        return np.eye(3, dtype=float)
    axis = axis / norm
    x, y, z = axis
    k = np.array(
        [
            [0.0, -z, y],
            [z, 0.0, -x],
            [-y, x, 0.0],
        ],
        dtype=float,
    )
    i = np.eye(3, dtype=float)
    return i + np.sin(angle) * k + (1.0 - np.cos(angle)) * (k @ k)


def _rotation_from_point_to_point(point: np.ndarray, previous_point: np.ndarray) -> np.ndarray:
    vector_to_previous_point = previous_point - point
    axis_of_rotation = np.array(
        [vector_to_previous_point[1], -vector_to_previous_point[0], 0.0],
        dtype=float,
    )
    theta = float(np.linalg.norm(vector_to_previous_point))
    return _rodrigues_rotation_matrix(axis_of_rotation, -theta)


def rotations_to_origin(path: np.ndarray) -> np.ndarray:
    pts = np.asarray(path, dtype=float)
    n = pts.shape[0]
    out = np.zeros((n, 3, 3), dtype=float)
    out[0] = np.eye(3, dtype=float)
    for i in range(1, n):
        step = _rotation_from_point_to_point(pts[i], pts[i - 1])
        out[i] = out[i - 1] @ step
    return out


def _rotation_angle(matrix: np.ndarray) -> float:
    cos_angle = (np.trace(matrix) - 1.0) / 2.0
    cos_angle = float(np.clip(cos_angle, -1.0, 1.0))
    return float(np.arccos(cos_angle))


def trace_on_sphere(path: np.ndarray, scale: float, core_radius: float = 1.0) -> np.ndarray:
    scaled = np.asarray(path, dtype=float) * float(scale)
    rotations = rotations_to_origin(scaled)
    start = np.array([0.0, 0.0, -core_radius], dtype=float)
    return np.einsum("nij,j->ni", rotations, start)


def mismatch_angle(path: np.ndarray, scale: float) -> float:
    scaled = np.asarray(path, dtype=float) * float(scale)
    net_rotation = rotations_to_origin(scaled)[-1]
    return _rotation_angle(net_rotation)


def _objective_for_scale(path: np.ndarray, scale: float, core_radius: float) -> float:
    scaled = np.asarray(path, dtype=float) * float(scale)
    rotations = rotations_to_origin(scaled)
    angle = _rotation_angle(rotations[-1])
    start = np.array([0.0, 0.0, -core_radius], dtype=float)
    trace = np.einsum("nij,j->ni", rotations, start)
    endpoint_gap = float(np.linalg.norm(trace[-1] - trace[0]))
    return angle + 0.75 * endpoint_gap


def estimate_scale(path: np.ndarray, core_radius: float = 1.0) -> Tuple[float, float, float]:
    plen = max(path_length(path), EPS)
    base = 2.0 * np.pi / plen
    lo = 0.2 * base
    hi = 5.0 * base
    minimize_scalar = _get_minimize_scalar()
    if minimize_scalar is not None:
        result = minimize_scalar(
            lambda s: _objective_for_scale(path, s, core_radius),
            bounds=(lo, hi),
            method="bounded",
            options={"xatol": 1e-4, "maxiter": 80},
        )
        scale = float(result.x if result.success else base)
    else:
        candidates = np.linspace(lo, hi, 80)
        values = [_objective_for_scale(path, s, core_radius) for s in candidates]
        scale = float(candidates[int(np.argmin(values))])
    scaled = np.asarray(path, dtype=float) * float(scale)
    rotations = rotations_to_origin(scaled)
    angle = _rotation_angle(rotations[-1])
    start = np.array([0.0, 0.0, -core_radius], dtype=float)
    trace = np.einsum("nij,j->ni", rotations, start)
    endpoint_gap = float(np.linalg.norm(trace[-1] - trace[0]))
    return scale, angle, endpoint_gap


def _compute_normals(path: np.ndarray, scale: float, core_radius: float, max_planes: int) -> np.ndarray:
    trace = trace_on_sphere(path, scale, core_radius=core_radius)
    normals = -trace / max(core_radius, EPS)
    if normals.shape[0] > max_planes:
        idx = np.linspace(0, normals.shape[0] - 1, max_planes).astype(int)
        normals = normals[idx]
    norms = np.linalg.norm(normals, axis=1, keepdims=True)
    return normals / np.maximum(norms, EPS)


def _implicit_field(
    normals: np.ndarray,
    outer_radius: float,
    core_radius: float,
    resolution: int,
    chunk_size: int = 40000,
    normal_batch: int = 96,
) -> Tuple[np.ndarray, np.ndarray]:
    lin = np.linspace(-outer_radius, outer_radius, resolution)
    res = int(resolution)
    total_points = res**3
    res2 = res * res
    normals_f64 = np.ascontiguousarray(normals, dtype=float)

    sphere_term = np.empty(total_points, dtype=float)
    plane_term = np.full(total_points, -np.inf, dtype=float)

    for p0 in range(0, total_points, chunk_size):
        p1 = min(total_points, p0 + chunk_size)
        flat_idx = np.arange(p0, p1, dtype=np.int64)
        ix = flat_idx // res2
        rem = flat_idx - ix * res2
        iy = rem // res
        iz = rem - iy * res

        chunk = np.empty((p1 - p0, 3), dtype=float)
        chunk[:, 0] = lin[ix]
        chunk[:, 1] = lin[iy]
        chunk[:, 2] = lin[iz]
        sphere_term[p0:p1] = np.linalg.norm(chunk, axis=1) - outer_radius

        chunk_max = np.full(chunk.shape[0], -np.inf, dtype=float)
        for n0 in range(0, normals_f64.shape[0], normal_batch):
            n1 = min(normals_f64.shape[0], n0 + normal_batch)
            # Some BLAS backends emit spurious overflow/invalid warnings here.
            with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
                dots = chunk @ normals_f64[n0:n1].T
            # Half-space constraint: dot(n, p) + core_radius >= 0 for every plane.
            viol = -(dots + core_radius)
            chunk_max = np.maximum(chunk_max, np.max(viol, axis=1))
        plane_term[p0:p1] = chunk_max

    field = np.maximum(sphere_term, plane_term).reshape((res, res, res))
    return lin, field


def _field_to_mesh(lin: np.ndarray, field: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    from skimage import measure

    if not (np.min(field) <= 0.0 <= np.max(field)):
        raise ValueError("No valid solid region found. Try a smoother or simpler curve.")
    spacing = float(lin[1] - lin[0])
    verts, faces, _, _ = measure.marching_cubes(field, level=0.0, spacing=(spacing, spacing, spacing))
    verts += np.array([lin[0], lin[0], lin[0]], dtype=float)
    return verts.astype(np.float32), faces.astype(np.int32)


def _clean_path(path_xy: np.ndarray) -> np.ndarray:
    points = np.asarray(path_xy, dtype=float)
    if points.ndim != 2 or points.shape[1] != 2:
        raise ValueError("Path must be an Nx2 array.")
    if points.shape[0] < 2:
        raise ValueError("Path has too few points for simulation.")
    deltas = np.linalg.norm(np.diff(points, axis=0), axis=1)
    keep_mask = np.ones(points.shape[0], dtype=bool)
    keep_mask[1:] = deltas > EPS
    points = points[keep_mask]
    if points.shape[0] < 2:
        raise ValueError("Path has no valid segments for simulation.")
    return points


def _sample_open_polyline_batch(points: np.ndarray, cumulative: np.ndarray, s_values: np.ndarray) -> np.ndarray:
    total = float(cumulative[-1])
    s_clamped = np.clip(np.asarray(s_values, dtype=float), 0.0, total)
    xs = np.interp(s_clamped, cumulative, points[:, 0])
    ys = np.interp(s_clamped, cumulative, points[:, 1])
    return np.column_stack([xs, ys])


def _tile_open_path(cycle_points: np.ndarray, n_cycles: int) -> np.ndarray:
    """Tile an open polyline by attaching each next copy to the previous endpoint.

    Each successive copy is rigidly transformed so that:
      - its starting point coincides with the previous copy's end point, and
      - its starting tangent matches the previous copy's ending tangent.

    This gives the natural "infinite extension" along which a trajectoid built
    from one period is meant to roll.
    """
    if n_cycles <= 1 or cycle_points.shape[0] < 2:
        return cycle_points.copy()

    p0 = cycle_points[0]
    centered = cycle_points - p0  # local copy with start at origin

    start_tangent = cycle_points[1] - cycle_points[0]
    end_tangent = cycle_points[-1] - cycle_points[-2]
    s_norm = float(np.linalg.norm(start_tangent))
    e_norm = float(np.linalg.norm(end_tangent))
    if s_norm < EPS or e_norm < EPS:
        rot_step = np.eye(2, dtype=float)
    else:
        s = start_tangent / s_norm
        e = end_tangent / e_norm
        cos_t = float(np.clip(s[0] * e[0] + s[1] * e[1], -1.0, 1.0))
        sin_t = float(s[0] * e[1] - s[1] * e[0])  # 2D cross: rotates s -> e
        rot_step = np.array([[cos_t, -sin_t], [sin_t, cos_t]], dtype=float)

    pieces = [cycle_points.copy()]
    cumulative_rot = np.eye(2, dtype=float)
    anchor = cycle_points[-1].copy()
    for _ in range(1, int(n_cycles)):
        cumulative_rot = rot_step @ cumulative_rot
        transformed = centered @ cumulative_rot.T + anchor
        # Drop the duplicated seam point so segment lengths stay intact.
        pieces.append(transformed[1:])
        anchor = transformed[-1]

    return np.vstack(pieces)


def build_roll_simulation(
    path_xy: np.ndarray,
    target_roll_angle_rad: float = 4 * np.pi,
    closed: bool = True,
    n_frames: int = 240,
    core_radius: float = 1.0,
) -> RollSimulationResult:
    points = _clean_path(path_xy)
    if core_radius <= 0:
        raise ValueError("core_radius must be positive.")
    n_frames = max(2, int(n_frames))

    if closed:
        if np.linalg.norm(points[0] - points[-1]) > EPS:
            cycle_points = np.vstack([points, points[0]])
        else:
            cycle_points = points.copy()
    else:
        cycle_points = points.copy()

    seg = np.linalg.norm(np.diff(cycle_points, axis=0), axis=1)
    cycle_len = float(np.sum(seg))
    if cycle_len < EPS:
        raise ValueError("Path length is too small to simulate rolling.")

    target_roll_angle_rad = float(max(0.0, target_roll_angle_rad))
    target_arc = target_roll_angle_rad * core_radius

    if closed:
        effective_arc = target_arc
        completed_target = True
        message = "Simulation reached the configured rolling target."
        cumulative = np.concatenate([[0.0], np.cumsum(seg)])
        arc_samples = np.linspace(0.0, effective_arc, n_frames)
        local_samples = np.mod(arc_samples, cycle_len)
        wrapped_endpoint = (arc_samples > 0.0) & np.isclose(local_samples, 0.0)
        local_samples[wrapped_endpoint] = cycle_len
        centers_xy = _sample_open_polyline_batch(cycle_points, cumulative, local_samples)
    else:
        # Tile the open one-period curve into a longer poly-period path so the
        # trajectoid keeps rolling forward instead of teleporting back to start.
        n_cycles_needed = int(np.ceil(target_arc / cycle_len)) if cycle_len > EPS else 1
        n_cycles_needed = max(1, n_cycles_needed)
        extended_points = _tile_open_path(cycle_points, n_cycles_needed)
        ext_seg = np.linalg.norm(np.diff(extended_points, axis=0), axis=1)
        extended_len = float(np.sum(ext_seg))
        cumulative = np.concatenate([[0.0], np.cumsum(ext_seg)])
        effective_arc = min(target_arc, extended_len)
        completed_target = effective_arc >= target_arc - 1e-6
        if completed_target:
            message = "Simulation reached the configured rolling target."
        else:
            message = (
                "Open trajectory ended before the configured rolling target. "
                "Simulation stopped at path end."
            )
        arc_samples = np.linspace(0.0, effective_arc, n_frames)
        local_samples = arc_samples
        centers_xy = _sample_open_polyline_batch(extended_points, cumulative, local_samples)

    translations = np.column_stack([centers_xy, np.full(n_frames, core_radius, dtype=float)])
    rotations = np.zeros((n_frames, 3, 3), dtype=float)
    rotations[0] = np.eye(3, dtype=float)

    achieved_roll_angle = 0.0
    for i in range(1, n_frames):
        delta = centers_xy[i] - centers_xy[i - 1]
        ds = float(np.linalg.norm(delta))
        if ds < EPS:
            rotations[i] = rotations[i - 1]
            continue
        # No-slip rolling: for travel direction v=(dx,dy,0) on the +z-up floor,
        # the body rotates about axis (-dy, dx, 0) (right-hand rule applied to
        # contact-point-stays-still constraint), giving the contact point a
        # velocity of -v in the body frame.
        axis = np.array([-delta[1], delta[0], 0.0], dtype=float)
        step = _rodrigues_rotation_matrix(axis, ds / core_radius)
        rotations[i] = step @ rotations[i - 1]
        achieved_roll_angle += ds / core_radius

    return RollSimulationResult(
        translations_xyz=translations,
        rotations=rotations,
        trajectory_xy=centers_xy.copy(),
        achieved_roll_angle_rad=float(achieved_roll_angle),
        completed_target=completed_target,
        message=message,
    )


def generate_trajectoid_mesh(
    input_path: np.ndarray,
    require_closed: bool = True,
    smooth_passes: int = 1,
    resample_points: int = 320,
    resolution: int = 96,
    core_radius: float = 1.0,
    outer_radius: float = 1.25,
    max_planes: int = 180,
) -> GenerationResult:
    points = np.asarray(input_path, dtype=float)
    validation = validate_path(points, require_closed=require_closed)
    if validation.errors:
        message = "\n".join(validation.errors + validation.suggestions)
        raise ValueError(message)

    is_closed = bool(require_closed)
    points = points - np.mean(points, axis=0, keepdims=True)
    points = smooth_path(points, passes=max(0, smooth_passes), closed=is_closed)
    points = resample_uniform(points, n_points=resample_points, closed=is_closed)

    scale, angle, endpoint_gap = estimate_scale(points, core_radius=core_radius)
    if angle > np.deg2rad(65.0):
        raise ValueError(
            "Generation is unstable: trajectory mismatch is too high.\n"
            "Try smooth + resample, simplify high-curvature corners, or redraw a more periodic curve."
        )

    normals = _compute_normals(points, scale=scale, core_radius=core_radius, max_planes=max_planes)
    lin, field = _implicit_field(
        normals=normals,
        outer_radius=outer_radius,
        core_radius=core_radius,
        resolution=resolution,
    )
    vertices, faces = _field_to_mesh(lin, field)
    contact_curve = trace_on_sphere(points, scale=scale, core_radius=core_radius)
    return GenerationResult(
        vertices=vertices,
        faces=faces,
        scale=scale,
        mismatch_angle=angle,
        endpoint_gap=endpoint_gap,
        resampled_points=points * scale,
        normals=normals,
        surface_contact_curve=contact_curve,
    )
